-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS states;
CREATE TABLE IF NOT EXISTS public.states 
(
    state_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    state_abbreviation character(2),
    population integer,
    state_property_tax_rate double precision
);
END;

-- Insert data into the table
INSERT INTO states
(state_name, state_abbreviation, population, state_property_tax_rate)
VALUES
('Florida','FL',21477737,0.0093),
('Alabama','AL',4903185,0.0042),
('Texas','TX',28995881,0.0181),
('Kentucky','KY',4467673,0.0086),
('Virginia','VA',8535519,0.0081),
('Louisiana', 'LA',4648794,0.0053),
('Utah','UT',3205958,0.0064),
('Vermont', 'VT',623989,0.0188);
SELECT state_name
FROM states
WHERE population > 5000000 AND state_property_tax_rate < 0.01;

-- Drop "customer" table if exists
DROP TABLE IF EXISTS customer;

-- Create the table "customer"
CREATE TABLE customer (
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30),
  gender VARCHAR(30),
  age INT,
  address VARCHAR(50),
  city VARCHAR(50),
  state CHAR(2),
  zip_code CHAR(5)
);

-- Insert data into the table (if empty)
INSERT INTO customer
(first_name, last_name, gender, age, address, city, state, zip_code)
VALUES
('Michael', 'Meyer', 'Male', 24, '1021 Eddie Knolls Apt. 087', 'South Geraldton', 'RI', 43709),
('Cindy', 'Stephens', 'Female', 23, '838 Brown Street', 'East Christina', 'MT', 07829),
('John', 'Jackson', 'Male', 34, '5319 Candice Motorway', 'Adkinstown', 'AZ', 89721),
('Alexander', 'Martinez', 'Male', 32, 'USNS Mosley', 'FPO', 'AA', 24673);

-- Insert duplicate records
INSERT INTO customer
(first_name, last_name, gender, age, address, city, state, zip_code)
VALUES
('Michael', 'Meyer', 'Male', 24, '1021 Eddie Knolls Apt. 087', 'South Geraldton', 'RI', 43709),
('Alexander', 'Martinez', 'Male', 32, 'USNS Mosley', 'FPO', 'AA', 24673);

-- Verify changes
SELECT *
FROM customer;
DROP TABLE IF EXISTS customer;
-- Re-create the table "customer"
-- with an incremental primary key
CREATE TABLE customer (
  customer_id SERIAL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30),
  gender VARCHAR(30),
  age INT,
  address VARCHAR(50),
  city VARCHAR(50),
  state CHAR(2),
  zip_code CHAR(5)
);


-- Insert duplicated data into the table after re-creating with an incremental primary key
INSERT INTO customer
(first_name, last_name, gender, age, address, city, state, zip_code)
VALUES
('Michael', 'Meyer', 'Male', 24, '1021 Eddie Knolls Apt. 087', 'South Geraldton', 'RI', 43709),
('Cindy', 'Stephens', 'Female', 23, '838 Brown Street', 'East Christina', 'MT', 07829),
('John', 'Jackson', 'Male', 34, '5319 Candice Motorway', 'Adkinstown', 'AZ', 89721),
('Alexander', 'Martinez', 'Male', 32, 'USNS Mosley', 'FPO', 'AA', 24673),
('Michael', 'Meyer', 'Male', 24, '1021 Eddie Knolls Apt. 087', 'South Geraldton', 'RI', 43709),
('Alexander', 'Martinez', 'Male', 32, 'USNS Mosley', 'FPO', 'AA', 24673);

-- Query all fields from the table
SELECT *
FROM customer;

-- Query the data to return all the rows containing the name "Michael"
SELECT customer_id, first_name, last_name, age
FROM customer
WHERE first_name = 'Michael';

-- Update a single row to change the `first_name` and `age` column data
UPDATE customer
SET first_name = 'Brian', age = 20
WHERE customer_id = 5;

SELECT *
FROM customer;

-- Delete the duplicate "Alexander Martinez" entry using a unique id
DELETE FROM customer
WHERE customer_id = 6;

SELECT *
FROM customer;
