-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
DROP TABLE IF EXISTS public.banks;
CREATE TABLE IF NOT EXISTS public.banks
(
    bank_id serial NOT NULL,
    bank_name character varying(50),
    bank_routing_number bigint,
    PRIMARY KEY (bank_id)
);

INSERT INTO public.banks
(bank_name, bank_routing_number)
VALUES
('Bank of America',12234),
('Cap One', 78964577),
('Cap One', 78964577);
SELECT *
FROM public.banks

DELETE FROM banks
WHERE bank_id = 3;